name: 🧩 Auto Update README

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Generate README
        run: python scripts/update_readme.py

      - name: Create Pull Request for README update
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update README with new problem(s) - ${{ github.sha }}"
          committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          branch: automation/update-readme
          title: "chore: update README with new problem(s)"
          body: |
            This automated PR updates **README.md** with newly added problem(s).
          labels: automated, readme
          paths: README.md
