name: README Generator
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Get Code
        uses: actions/checkout@v4
      
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
        
      - name: Run README Generator
        run: python scripts/update_readme.py
      - name: Commit README if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md || true
          if ! git diff --staged --quiet; then
            git commit -m "chore: update README with new problem(s) - ${{ github.sha }}"
            git push
          else
            echo "No README changes to commit"
          fi
      